### ISSUE TITLE
java.lang.ClassNotFoundException: scala.meta.metals.Main

### ISSUE THREAD

**Issue by tym-network** [scalameta/metals-vscode#366]
**Describe the bug**

Metals server crashes when opening a Scala project.

**To Reproduce**

1. Open a Scala project in VSCode
2. In the Notification drawer, it says "Starting Metals server..."
3. After a few seconds, the following error in displayed in the notification server: "The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted."

**Expected behavior**

The Metals server starts properly.

**Screenshots**
![Metals1](https://user-images.githubusercontent.com/2879545/88508390-8e22aa00-cf93-11ea-9156-87a5ca64988c.png)
![Metals2](https://user-images.githubusercontent.com/2879545/88508391-8ebb4080-cf93-11ea-8c64-46a3bcee4fd6.png)

**Installation:**

- Operating system: Windows 10
- VSCode version: 1.47.2
- VSCode extension version: 1.9.2
- Metals version: 0.9.2

**Additional context**

Here is the content of the log file located in AppData/Roaming/Code/logs/xxx/exthost1/output_logging_xxx:
```
Java home: C:\Program Files\Java\jdk-11.0.8
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Info  - 22:51:16] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Info  - 22:51:17] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Info  - 22:51:17] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Info  - 22:51:17] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Error - 22:51:17] Connection to server got closed. Server will not be restarted.
```

I installed Java 11 and specified the path in VSCode settings `metals.javaHome`.
I also installed Scala using the .exe

Could the error be because I have an accent in my first name (which is also in the name of my home folder)? 

**Search terms**
metals server crashed ClassNotFoundException main

**Comment by tgodzik** [comment]
Thanks for reporting! The issue might be coming from having the additional accent, though I hoped this was fixed recently. Especially that it seems to be running Java properly. I will try to reproduce it locally. 

Did you try reloading the window maybe? I've seen situation where the Main class of the server was not detected at first, however I have no idea why.

**Comment by tym-network** [comment]
Thanks for your blazing fast answer!

Unfortunately, I have the error every time I open VSCode... I've never been able to make it work. Reloading the window or re-opening VSCode doesn't solve the issue.

**Comment by tgodzik** [comment]
Ok, I can reproduce the issue on Windows. It doesn't seem to cope well with accents.

**Comment by vikas-saxena02** [comment]
Hi guys, I am getting the same error on Metals 1.2, can you please elaborate on how to bypass it. I do not have accents in username on my system which is RHEL 7.9 running VScode 1.85.2

**Comment by divijan** [comment]
I'm facing a similar problem:
```
Metals version: 1.3.1
Using coursier located at C:\Users\Пп\.metals\cs.exe
C:\Program Files\Eclipse Adoptium\jdk-17.0.11.9-hotspot\bin\java -version:
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
Using Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.11.9-hotspot\
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Error - 6:05:42 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:05:42 PM] Connection to server got closed. Server will restart.
true
[Error - 6:05:42 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Error - 6:05:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:05:43 PM] Connection to server got closed. Server will restart.
true
[Error - 6:05:43 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not launch Metals Language Server:
Pending response rejected since connection got disposed
Release notes was not shown: not showing release notes since they've already been seen for your current version
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Error - 6:05:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:05:43 PM] Connection to server got closed. Server will restart.
true
[Error - 6:05:43 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:05:43 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Error - 6:05:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:05:43 PM] Connection to server got closed. Server will restart.
true
[Error - 6:05:43 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:05:43 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error: Could not find or load main class scala.meta.metals.Main
Caused by: java.lang.ClassNotFoundException: scala.meta.metals.Main
[Error - 6:05:44 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:05:44 PM] The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 6:05:44 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:05:44 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```
I have changed my home directory name here in input, the point is, it is Cyrillic. I'm running Windows 10

**Comment by divijan** [comment]
@vikas-saxena02 any luck with your problem? I'm having the same thing

**Comment by vikas-saxena02** [comment]
@divijan Metals does require a lot of dependencies available to it in order to start which need to come from either mavencentral or if you are in a an airgap system like me from your local package repository such as artificatory or Nexus.
If its the later, you will need to go to settings -> Metals  and point the following properties to your  repository.
- Coursier Mirror
- Custom Repositories
